// frontend/src/components/layout/Header.tsx
import * as React from "react";
import { Menu } from "lucide-react";

import { ThemeToggle } from "@/components/common/ThemeToggle";
import { useChatStore } from "@/stores/chatStore";

interface HeaderProps {
  onToggleSidebar: () => void;
}

export function Header({ onToggleSidebar }: HeaderProps) {
  const { currentSessionId, sessions } = useChatStore();
  const currentSession = React.useMemo(
    () => sessions.find((session) => session.id === currentSessionId),
    [sessions, currentSessionId]
  );

  return (
    <header className="chat-header">
      <div className="chat-header__leading">
        <button
          type="button"
          onClick={onToggleSidebar}
          aria-label="打开会话列表"
          className="chat-header__menu"
        >
          <Menu className="h-5 w-5" />
        </button>
        <p className="chat-header__title">{currentSession?.title || "新对话"}</p>
      </div>
      <ThemeToggle />
    </header>
  );
}

// frontend/src/components/layout/Header.vue
<template>
  <header class="chat-header">
    <div class="chat-header__leading">
      <button
        type="button"
        class="chat-header__menu"
        aria-label="打开会话列表"
        @click="$emit('toggle-sidebar')"
      >
        <Menu :size="20" />
      </button>
      <p class="chat-header__title">{{ currentSession?.title || "新对话" }}</p>
    </div>
    <ThemeToggle />
  </header>
</template>

<script setup lang="ts">
import { Menu } from "lucide-vue-next";
import { storeToRefs } from "pinia";
import { computed } from "vue";

import ThemeToggle from "@/components/layout/ThemeToggle.vue";
import { useChatStore } from "@/stores/chat";

defineEmits<{ (event: "toggle-sidebar"): void }>();

const chat = useChatStore();
const { sessions, currentSessionId } = storeToRefs(chat);
const currentSession = computed(() =>
  sessions.value.find((session) => session.id === currentSessionId.value)
);
</script>
