// frontend/src/components/layout/MainLayout.vue
<template>
  <div class="chat-shell">
    <Sidebar :open="sidebarOpen" @close="sidebarOpen = false" />
    <div class="chat-shell__main">
      <Header @toggle-sidebar="sidebarOpen = !sidebarOpen" />
      <main class="chat-shell__content">
        <slot />
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

import Header from "@/components/layout/Header.vue";
import Sidebar from "@/components/layout/Sidebar.vue";

const sidebarOpen = ref(false);
</script>

// frontend/src/components/layout/MainLayout.tsx
import * as React from "react";

import { Header } from "@/components/layout/Header";
import { Sidebar } from "@/components/layout/Sidebar";

interface MainLayoutProps {
  children: React.ReactNode;
}

export function MainLayout({ children }: MainLayoutProps) {
  const [sidebarOpen, setSidebarOpen] = React.useState(false);

  return (
    <div className="chat-shell">
      <Sidebar isOpen={sidebarOpen} onClose={() => setSidebarOpen(false)} />
      <div className="chat-shell__main">
        <Header onToggleSidebar={() => setSidebarOpen((prev) => !prev)} />
        <main className="chat-shell__content">{children}</main>
      </div>
    </div>
  );
}
