// frontend/src/components/chat/ChatInput.tsx
import * as React from "react";
import { Brain, Send, Square } from "lucide-react";

import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";
import { useChatStore } from "@/stores/chatStore";

export function ChatInput() {
  const [value, setValue] = React.useState("");
  const [isFocused, setIsFocused] = React.useState(false);
  const isComposingRef = React.useRef(false);
  const textareaRef = React.useRef<HTMLTextAreaElement | null>(null);
  const {
    sendMessage,
    isStreaming,
    cancelGeneration,
    deepThinkingEnabled,
    setDeepThinkingEnabled,
    inputFocusKey
  } = useChatStore();

  const focusInput = React.useCallback(() => {
    const el = textareaRef.current;
    if (!el) return;
    el.focus({ preventScroll: true });
  }, []);

  const adjustHeight = React.useCallback(() => {
    const el = textareaRef.current;
    if (!el) return;
    el.style.height = "auto";
    const next = Math.min(el.scrollHeight, 160);
    el.style.height = `${next}px`;
  }, []);

  React.useEffect(() => {
    adjustHeight();
  }, [value, adjustHeight]);

  React.useEffect(() => {
    if (!inputFocusKey) return;
    focusInput();
  }, [inputFocusKey, focusInput]);

  const handleSubmit = async () => {
    if (isStreaming) {
      cancelGeneration();
      focusInput();
      return;
    }
    if (!value.trim()) return;
    const next = value;
    setValue("");
    focusInput();
    await sendMessage(next);
    focusInput();
  };

  const hasContent = value.trim().length > 0;

  return (
    <div className="chat-composer-wrap">
      <div className={cn("chat-composer", isFocused && "chat-composer--focused")}>
        <Textarea
          ref={textareaRef}
          value={value}
          onChange={(event) => setValue(event.target.value)}
          placeholder={deepThinkingEnabled ? "输入需要深入分析的问题" : "给 Ragent 发送消息"}
          className="chat-composer__input"
          rows={1}
          onFocus={() => setIsFocused(true)}
          onBlur={() => setIsFocused(false)}
          onCompositionStart={() => { isComposingRef.current = true; }}
          onCompositionEnd={() => { isComposingRef.current = false; }}
          onKeyDown={(event) => {
            if (event.key === "Enter" && !event.shiftKey) {
              const nativeEvent = event.nativeEvent as KeyboardEvent;
              if (nativeEvent.isComposing || isComposingRef.current || nativeEvent.keyCode === 229) return;
              event.preventDefault();
              handleSubmit();
            }
          }}
          aria-label="聊天输入框"
        />
        <div className="chat-composer__toolbar">
          <button
            type="button"
            onClick={() => setDeepThinkingEnabled(!deepThinkingEnabled)}
            disabled={isStreaming}
            aria-pressed={deepThinkingEnabled}
            className={cn("chat-composer__mode", deepThinkingEnabled && "is-active")}
          >
            <Brain className="h-4 w-4" />
            深度思考
          </button>
          <button
            type="button"
            onClick={handleSubmit}
            disabled={!hasContent && !isStreaming}
            aria-label={isStreaming ? "停止生成" : "发送消息"}
            className={cn("chat-composer__send", isStreaming && "is-stopping")}
          >
            {isStreaming ? <Square className="h-4 w-4" /> : <Send className="h-4 w-4" />}
          </button>
        </div>
      </div>
      <p className="chat-composer__hint">
        {isStreaming ? "正在生成回答…" : "Ragent 可能会出错，请核对重要信息。"}
      </p>
    </div>
  );
}

// frontend/src/components/chat/ChatInput.vue
<template>
  <div class="chat-composer-wrap">
    <div class="chat-composer" :class="{ 'chat-composer--focused': focused }">
      <textarea
        ref="textareaRef"
        v-model="value"
        class="chat-composer__input"
        rows="1"
        :placeholder="deepThinkingEnabled ? '输入需要深入分析的问题' : '给 Ragent 发送消息'"
        aria-label="聊天输入框"
        @focus="focused = true"
        @blur="focused = false"
        @compositionstart="composing = true"
        @compositionend="composing = false"
        @keydown="handleKeydown"
        @input="adjustHeight"
      ></textarea>
      <div class="chat-composer__toolbar">
        <button
          type="button"
          class="chat-composer__mode"
          :class="{ 'is-active': deepThinkingEnabled }"
          :disabled="isStreaming"
          :aria-pressed="deepThinkingEnabled"
          @click="chat.deepThinkingEnabled = !chat.deepThinkingEnabled"
        >
          <Brain :size="16" />
          深度思考
        </button>
        <button
          type="button"
          class="chat-composer__send"
          :class="{ 'is-stopping': isStreaming }"
          :disabled="!hasContent && !isStreaming"
          :aria-label="isStreaming ? '停止生成' : '发送消息'"
          @click="handleSubmit"
        >
          <Square v-if="isStreaming" :size="16" fill="currentColor" />
          <Send v-else :size="16" />
        </button>
      </div>
    </div>
    <p class="chat-composer__hint">
      {{ isStreaming ? "正在生成回答…" : "Ragent 可能会出错，请核对重要信息。" }}
    </p>
  </div>
</template>

<script setup lang="ts">
import { Brain, Send, Square } from "lucide-vue-next";
import { storeToRefs } from "pinia";
import { computed, nextTick, ref } from "vue";

import { useChatStore } from "@/stores/chat";

const chat = useChatStore();
const { isStreaming, deepThinkingEnabled } = storeToRefs(chat);
const value = ref("");
const focused = ref(false);
const composing = ref(false);
const textareaRef = ref<HTMLTextAreaElement | null>(null);
const hasContent = computed(() => value.value.trim().length > 0);

function focusInput() {
  void nextTick(() => textareaRef.value?.focus({ preventScroll: true }));
}

function adjustHeight() {
  void nextTick(() => {
    const textarea = textareaRef.value;
    if (!textarea) return;
    textarea.style.height = "auto";
    textarea.style.height = `${Math.min(textarea.scrollHeight, 160)}px`;
  });
}

function handleKeydown(event: KeyboardEvent) {
  if (event.key !== "Enter" || event.shiftKey) return;
  if (event.isComposing || composing.value || event.keyCode === 229) return;
  event.preventDefault();
  handleSubmit();
}

function handleSubmit() {
  if (isStreaming.value) {
    chat.cancelGeneration();
    focusInput();
    return;
  }

  const next = value.value.trim();
  if (!next) return;
  value.value = "";
  adjustHeight();
  focusInput();
  void chat.sendMessage(next);
}
</script>
