// frontend/src/components/chat/MessageList.tsx
import * as React from "react";
import { Virtuoso, type VirtuosoHandle } from "react-virtuoso";

import { MessageItem } from "@/components/chat/MessageItem";
import { QuestionRail, type QuestionRailItem } from "@/components/chat/QuestionRail";
import { WelcomeScreen } from "@/components/chat/WelcomeScreen";
import { cn } from "@/lib/utils";
import type { Message } from "@/types";

interface MessageListProps {
  messages: Message[];
  isLoading: boolean;
  isStreaming: boolean;
  sessionKey?: string | null;
}

export function MessageList({ messages, isLoading, isStreaming, sessionKey }: MessageListProps) {
  const virtuosoRef = React.useRef<VirtuosoHandle | null>(null);
  const scrollerRef = React.useRef<HTMLElement | null>(null);
  const lastSessionRef = React.useRef<string | null>(null);
  const pendingScrollRef = React.useRef(true);
  const settleTimerRef = React.useRef<number | null>(null);
  const heightScrollRafRef = React.useRef<number | null>(null);
  const prevStreamingRef = React.useRef(false);
  const initialTopMostItemIndex = React.useMemo(
    () => ({ index: "LAST" as const, align: "end" as const }),
    []
  );
  const [visibleEnd, setVisibleEnd] = React.useState(0);

  const userQuestions = React.useMemo<QuestionRailItem[]>(() => {
    const items: QuestionRailItem[] = [];
    messages.forEach((msg, flatIndex) => {
      if (msg.role !== "user") return;
      const text = msg.content.replace(/\s+/g, " ").trim();
      if (!text) return;
      items.push({ id: msg.id, flatIndex, text });
    });
    return items;
  }, [messages]);

  const activeQuestionId = React.useMemo(() => {
    if (userQuestions.length === 0) return null;
    let last: string | null = userQuestions[0].id;
    for (const q of userQuestions) {
      if (q.flatIndex <= visibleEnd) {
        last = q.id;
      } else {
        break;
      }
    }
    return last;
  }, [userQuestions, visibleEnd]);

  const handleSelectQuestion = React.useCallback((flatIndex: number) => {
    virtuosoRef.current?.scrollToIndex({
      index: flatIndex,
      align: "start",
      behavior: "smooth"
    });
  }, []);

  const handleRangeChanged = React.useCallback(
    (range: { startIndex: number; endIndex: number }) => {
      setVisibleEnd(range.endIndex);
    },
    []
  );

  const scrollToBottom = React.useCallback(() => {
    virtuosoRef.current?.scrollToIndex({ index: "LAST", align: "end", behavior: "auto" });
    const scroller = scrollerRef.current;
    if (scroller) {
      scroller.scrollTop = scroller.scrollHeight;
    }
  }, []);

  const stickToBottom = React.useCallback(() => {
    const scroller = scrollerRef.current;
    if (!scroller) return;
    scroller.scrollTop = scroller.scrollHeight;
  }, []);

  React.useEffect(() => {
    const nextKey = sessionKey ?? "empty";
    if (lastSessionRef.current !== nextKey) {
      lastSessionRef.current = nextKey;
      pendingScrollRef.current = true;
      if (settleTimerRef.current) {
        window.clearTimeout(settleTimerRef.current);
        settleTimerRef.current = null;
      }
    }
  }, [sessionKey]);

  React.useEffect(() => {
    const wasStreaming = prevStreamingRef.current;
    prevStreamingRef.current = isStreaming;
    if (!wasStreaming && isStreaming) {
      stickToBottom();
      const timer = window.setTimeout(stickToBottom, 120);
      return () => window.clearTimeout(timer);
    }
    if (wasStreaming && !isStreaming) {
      scrollToBottom();
      const timer = window.setTimeout(scrollToBottom, 120);
      const lateTimer = window.setTimeout(scrollToBottom, 360);
      return () => {
        window.clearTimeout(timer);
        window.clearTimeout(lateTimer);
      };
    }
    return;
  }, [isStreaming, stickToBottom, scrollToBottom]);

  React.useLayoutEffect(() => {
    if (!pendingScrollRef.current || isStreaming || isLoading || messages.length === 0) {
      return;
    }
    let attempts = 0;
    let rafId = 0;
    let active = true;
    const run = () => {
      scrollToBottom();
      attempts += 1;
      if (attempts < 3) {
        rafId = window.requestAnimationFrame(run);
      }
    };
    run();
    const timer = window.setTimeout(scrollToBottom, 240);
    const lateTimer = window.setTimeout(scrollToBottom, 900);
    const handleLoad = () => {
      if (active) {
        scrollToBottom();
      }
    };
    if (document.readyState === "complete") {
      handleLoad();
    } else {
      window.addEventListener("load", handleLoad, { once: true });
    }
    if (document.fonts?.ready) {
      document.fonts.ready.then(() => {
      if (active) {
        scrollToBottom();
      }
    });
  }
    if (settleTimerRef.current) {
      window.clearTimeout(settleTimerRef.current);
    }
    settleTimerRef.current = window.setTimeout(() => {
      pendingScrollRef.current = false;
      settleTimerRef.current = null;
    }, 1500);
    return () => {
      active = false;
      window.cancelAnimationFrame(rafId);
      window.clearTimeout(timer);
      window.clearTimeout(lateTimer);
      if (settleTimerRef.current) {
        window.clearTimeout(settleTimerRef.current);
        settleTimerRef.current = null;
      }
      window.removeEventListener("load", handleLoad);
    };
  }, [messages.length, isStreaming, isLoading, sessionKey]);

  React.useEffect(() => {
    return () => {
      if (heightScrollRafRef.current) {
        window.cancelAnimationFrame(heightScrollRafRef.current);
        heightScrollRafRef.current = null;
      }
      if (settleTimerRef.current) {
        window.clearTimeout(settleTimerRef.current);
        settleTimerRef.current = null;
      }
    };
  }, []);

  const handleTotalListHeightChanged = React.useCallback(() => {
    if (isLoading) {
      return;
    }
    const shouldStick = isStreaming || pendingScrollRef.current;
    if (!shouldStick) return;
    if (heightScrollRafRef.current) {
      return;
    }
    heightScrollRafRef.current = window.requestAnimationFrame(() => {
      heightScrollRafRef.current = null;
      if (isStreaming) {
        stickToBottom();
      } else {
        scrollToBottom();
      }
    });
  }, [isStreaming, isLoading, scrollToBottom, stickToBottom]);

  // Intercept triple-click at mousedown phase to prevent browser from
  // extending paragraph selection across sibling message boundaries.
  // preventDefault() stops the default selection, then we manually select
  // only the clicked block-level element's contents.
  const handleTripleClickDown = React.useCallback((e: React.MouseEvent<HTMLDivElement>) => {
    if (e.detail < 3) return;
    e.preventDefault();
    const target = e.target as HTMLElement;
    const block = target.closest("p, li, h1, h2, h3, h4, h5, h6, pre, blockquote, td, th");
    const container = block && e.currentTarget.contains(block) ? block : e.currentTarget;
    const sel = window.getSelection();
    if (sel) {
      const range = document.createRange();
      range.selectNodeContents(container);
      sel.removeAllRanges();
      sel.addRange(range);
    }
  }, []);

  const List = React.useMemo(() => {
    const Comp = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
      ({ className, ...props }, ref) => (
        <div
          ref={ref}
          className={cn("mx-auto max-w-[840px] space-y-10 px-6 pt-10 pb-2 md:px-8", className)}
          {...props}
        />
      )
    );
    Comp.displayName = "MessageList";
    return Comp;
  }, []);

  const Footer = React.useMemo(() => {
    const Comp = () => <div aria-hidden="true" className="h-8" />;
    Comp.displayName = "MessageListFooter";
    return Comp;
  }, []);

  if (messages.length === 0) {
    if (isLoading) {
      return <div className="h-full" />;
    }
    return <WelcomeScreen />;
  }

  return (
    <div className="relative h-full">
      <Virtuoso
        key={sessionKey ?? "empty"}
        ref={virtuosoRef}
        data={messages}
        initialTopMostItemIndex={initialTopMostItemIndex}
        followOutput={(atBottom) => {
          if (isStreaming) return false;
          return atBottom ? "auto" : false;
        }}
        scrollerRef={(node) => {
          scrollerRef.current = node as HTMLElement | null;
        }}
        totalListHeightChanged={handleTotalListHeightChanged}
        rangeChanged={handleRangeChanged}
        className="h-full"
        components={{ List, Footer }}
        itemContent={(index, message) => (
          <div
            className={cn(index === messages.length - 1 && "animate-fade-up")}
            onMouseDown={handleTripleClickDown}
          >
            <MessageItem message={message} isLast={index === messages.length - 1} />
          </div>
        )}
      />
      <QuestionRail
        items={userQuestions}
        activeId={activeQuestionId}
        onSelect={handleSelectQuestion}
      />
    </div>
  );
}

// frontend/src/components/chat/MessageList.vue
<template>
  <div v-if="messages.length === 0" class="message-list-empty">
    <div v-if="isLoading" class="message-list-loading"></div>
    <WelcomeScreen v-else />
  </div>

  <div v-else class="message-list-shell">
    <div ref="scrollerRef" class="message-list" @scroll="updateActiveQuestion">
      <div class="message-list__inner">
        <div
          v-for="(message, index) in messages"
          :key="message.id"
          :data-message-id="message.id"
          @mousedown="handleTripleClick"
        >
          <MessageItem :message="message" :is-last="index === messages.length - 1" />
        </div>
        <div class="message-list__footer" aria-hidden="true"></div>
      </div>
    </div>
    <QuestionRail :items="userQuestions" :active-id="activeQuestionId" @select="scrollToQuestion" />
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from "vue";

import MessageItem from "@/components/chat/MessageItem.vue";
import QuestionRail, { type QuestionRailItem } from "@/components/chat/QuestionRail.vue";
import WelcomeScreen from "@/components/chat/WelcomeScreen.vue";
import type { Message } from "@/types";

const props = defineProps<{
  messages: Message[];
  isLoading: boolean;
  isStreaming: boolean;
  sessionKey?: string | null;
}>();

const scrollerRef = ref<HTMLElement | null>(null);
const activeQuestionId = ref<string | null>(null);
let settleTimer: ReturnType<typeof setTimeout> | null = null;

const userQuestions = computed<QuestionRailItem[]>(() =>
  props.messages
    .filter((message) => message.role === "user" && message.content.trim())
    .map((message) => ({ id: message.id, text: message.content.replace(/\s+/g, " ").trim() }))
);

function scrollToBottom() {
  void nextTick(() => {
    const scroller = scrollerRef.value;
    if (scroller) scroller.scrollTop = scroller.scrollHeight;
  });
}

function settleAtBottom() {
  scrollToBottom();
  if (settleTimer) clearTimeout(settleTimer);
  settleTimer = setTimeout(scrollToBottom, 220);
}

function scrollToQuestion(messageId: string) {
  const target = scrollerRef.value?.querySelector<HTMLElement>(`[data-message-id="${CSS.escape(messageId)}"]`);
  target?.scrollIntoView({ block: "start", behavior: "smooth" });
}

function updateActiveQuestion() {
  const scroller = scrollerRef.value;
  if (!scroller || userQuestions.value.length === 0) {
    activeQuestionId.value = null;
    return;
  }
  const top = scroller.getBoundingClientRect().top + 48;
  let active = userQuestions.value[0].id;
  for (const question of userQuestions.value) {
    const node = scroller.querySelector<HTMLElement>(`[data-message-id="${CSS.escape(question.id)}"]`);
    if (node && node.getBoundingClientRect().top <= top) active = question.id;
  }
  activeQuestionId.value = active;
}

function handleTripleClick(event: MouseEvent) {
  if (event.detail < 3) return;
  event.preventDefault();
  const target = event.target as HTMLElement;
  const message = event.currentTarget as HTMLElement;
  const block = target.closest("p, li, h1, h2, h3, h4, h5, h6, pre, blockquote, td, th");
  const container = block && message.contains(block) ? block : message;
  const selection = window.getSelection();
  if (!selection) return;
  const range = document.createRange();
  range.selectNodeContents(container);
  selection.removeAllRanges();
  selection.addRange(range);
}

watch(
  () => props.sessionKey,
  () => settleAtBottom(),
  { immediate: true }
);

watch(
  () => [props.messages.length, props.messages.at(-1)?.content, props.messages.at(-1)?.thinking, props.isStreaming],
  () => {
    if (props.isStreaming) scrollToBottom();
    else settleAtBottom();
    void nextTick(updateActiveQuestion);
  }
);

onBeforeUnmount(() => {
  if (settleTimer) clearTimeout(settleTimer);
});
</script>
