// frontend/src/components/chat/ThinkingIndicator.vue
<template>
  <div class="thinking-status" role="status">
    <LoaderCircle :size="16" />
    <span>{{ content?.trim() || "正在分析知识库…" }}</span>
    <span v-if="duration" class="thinking-status__duration">{{ duration }} 秒</span>
  </div>
</template>

<script setup lang="ts">
import { LoaderCircle } from "lucide-vue-next";

defineProps<{ content?: string; duration?: number }>();
</script>

// frontend/src/components/chat/ThinkingIndicator.tsx
import { Loader2 } from "lucide-react";

interface ThinkingIndicatorProps {
  content?: string;
  duration?: number;
}

export function ThinkingIndicator({ content, duration }: ThinkingIndicatorProps) {
  return (
    <div className="thinking-status" role="status">
      <Loader2 className="h-4 w-4 animate-spin" />
      <span>{content?.trim() || "正在分析知识库…"}</span>
      {duration ? <span className="thinking-status__duration">{duration} 秒</span> : null}
    </div>
  );
}
