// frontend/src/pages/ChatPage.vue
<template>
  <MainLayout>
    <div class="chat-page">
      <div class="chat-page__messages">
        <MessageList
          :messages="messages"
          :is-loading="isLoading"
          :is-streaming="isStreaming"
          :session-key="currentSessionId"
        />
      </div>
      <div v-if="!showWelcome" class="chat-page__composer">
        <ChatInput />
      </div>
    </div>
  </MainLayout>
</template>

<script setup lang="ts">
import { storeToRefs } from "pinia";
import { computed, onMounted, ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";

import ChatInput from "@/components/chat/ChatInput.vue";
import MessageList from "@/components/chat/MessageList.vue";
import MainLayout from "@/components/layout/MainLayout.vue";
import { useChatStore } from "@/stores/chat";

const route = useRoute();
const router = useRouter();
const chat = useChatStore();
const { messages, isLoading, isStreaming, currentSessionId, sessions, isCreatingNew } = storeToRefs(chat);
const sessionsReady = ref(false);

const showWelcome = computed(() => messages.value.length === 0 && !isLoading.value);

async function syncRouteSession(sessionId: unknown) {
  if (!sessionsReady.value) return;

  if (typeof sessionId === "string" && sessionId) {
    if (!sessions.value.some((session) => session.id === sessionId)) {
      chat.createSession();
      await router.replace("/chat");
      return;
    }
    await chat.selectSession(sessionId);
    return;
  }

  if (!isCreatingNew.value && !currentSessionId.value) {
    chat.createSession();
  }
}

watch(
  () => route.params.sessionId,
  (sessionId) => {
    void syncRouteSession(sessionId);
  }
);

watch(currentSessionId, (sessionId) => {
  if (sessionId && route.params.sessionId !== sessionId) {
    void router.replace(`/chat/${sessionId}`);
  }
});

onMounted(async () => {
  if (!chat.sessionsLoaded) {
    await chat.fetchSessions();
  }
  sessionsReady.value = true;
  await syncRouteSession(route.params.sessionId);
});
</script>

// frontend/src/pages/ChatPage.tsx
import * as React from "react";
import { useNavigate, useParams } from "react-router-dom";

import { ChatInput } from "@/components/chat/ChatInput";
import { MessageList } from "@/components/chat/MessageList";
import { MainLayout } from "@/components/layout/MainLayout";
import { useChatStore } from "@/stores/chatStore";

export function ChatPage() {
  const navigate = useNavigate();
  const { sessionId } = useParams<{ sessionId: string }>();
  const {
    messages,
    isLoading,
    isStreaming,
    currentSessionId,
    sessions,
    isCreatingNew,
    fetchSessions,
    selectSession,
    createSession
  } = useChatStore();
  const showWelcome = messages.length === 0 && !isLoading;
  const [sessionsReady, setSessionsReady] = React.useState(false);
  const sessionExists = React.useMemo(() => {
    if (!sessionId) return false;
    return sessions.some((session) => session.id === sessionId);
  }, [sessionId, sessions]);

  React.useEffect(() => {
    let active = true;
    fetchSessions()
      .catch(() => null)
      .finally(() => {
        if (active) {
          setSessionsReady(true);
        }
      });
    return () => {
      active = false;
    };
  }, [fetchSessions]);

  React.useEffect(() => {
    if (sessionId) {
      if (sessionsReady && !sessionExists) {
        createSession().catch(() => null);
        navigate("/chat", { replace: true });
        return;
      }
      selectSession(sessionId).catch(() => null);
      return;
    }
    if (!sessionsReady) {
      return;
    }
    if (isCreatingNew) {
      return;
    }
    if (currentSessionId) {
      return;
    }
    createSession().catch(() => null);
  }, [
    sessionId,
    sessionsReady,
    sessionExists,
    isCreatingNew,
    currentSessionId,
    selectSession,
    createSession,
    navigate
  ]);

  React.useEffect(() => {
    if (currentSessionId && currentSessionId !== sessionId) {
      navigate(`/chat/${currentSessionId}`, { replace: true });
    }
  }, [currentSessionId, sessionId, navigate]);

  return (
    <MainLayout>
      <div className="chat-page">
        <div className="chat-page__messages">
          <MessageList
            messages={messages}
            isLoading={isLoading}
            isStreaming={isStreaming}
            sessionKey={currentSessionId}
          />
        </div>
        {showWelcome ? null : (
          <div className="chat-page__composer">
            <ChatInput />
          </div>
        )}
      </div>
    </MainLayout>
  );
}
