// frontend/src/pages/LoginPage.vue
<template>
  <main class="login-page">
    <div class="login-page__theme">
      <ThemeToggle />
    </div>

    <section class="login-card">
      <div class="login-card__brand" aria-hidden="true">R</div>
      <h1>登录 Ragent</h1>
      <p>使用你的账号继续访问知识问答。</p>

      <form class="login-form" @submit.prevent="handleLogin">
        <div class="login-field">
          <label for="username">用户名</label>
          <input
            id="username"
            v-model="username"
            class="ui-input"
            autocomplete="username"
            autofocus
            placeholder="请输入用户名"
          />
        </div>

        <div class="login-field">
          <label for="password">密码</label>
          <div class="login-password">
            <input
              id="password"
              v-model="password"
              class="ui-input"
              :type="showPassword ? 'text' : 'password'"
              autocomplete="current-password"
              placeholder="请输入密码"
            />
            <button
              type="button"
              :aria-label="showPassword ? '隐藏密码' : '显示密码'"
              @click="showPassword = !showPassword"
            >
              <EyeOff v-if="showPassword" :size="16" />
              <Eye v-else :size="16" />
            </button>
          </div>
        </div>

        <p v-if="errorMessage" class="login-error" role="alert">{{ errorMessage }}</p>
        <button class="login-submit" type="submit" :disabled="loading">
          {{ loading ? "正在登录…" : "登录" }}
        </button>
      </form>
    </section>
  </main>
</template>

<script setup lang="ts">
import { Eye, EyeOff } from "lucide-vue-next";
import { ref } from "vue";
import { useRoute, useRouter } from "vue-router";

import ThemeToggle from "@/components/layout/ThemeToggle.vue";
import { useAuthStore } from "@/stores/auth";

const auth = useAuthStore();
const route = useRoute();
const router = useRouter();
const username = ref("");
const password = ref("");
const showPassword = ref(false);
const loading = ref(false);
const errorMessage = ref<string | null>(null);

async function handleLogin() {
  errorMessage.value = null;
  if (!username.value.trim() || !password.value.trim()) {
    errorMessage.value = "请输入用户名和密码。";
    return;
  }

  loading.value = true;
  try {
    await auth.login(username.value.trim(), password.value.trim());
    await router.replace(String(route.query.redirect || "/chat"));
  } catch (error) {
    errorMessage.value = (error as Error).message || "登录失败，请稍后重试。";
  } finally {
    loading.value = false;
  }
}
</script>

// frontend/src/pages/LoginPage.tsx
import * as React from "react";
import { Eye, EyeOff } from "lucide-react";
import { useNavigate } from "react-router-dom";

import { ThemeToggle } from "@/components/common/ThemeToggle";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuthStore } from "@/stores/authStore";

export function LoginPage() {
  const navigate = useNavigate();
  const { login, isLoading } = useAuthStore();
  const [showPassword, setShowPassword] = React.useState(false);
  const [form, setForm] = React.useState({ username: "", password: "" });
  const [error, setError] = React.useState<string | null>(null);

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    setError(null);
    if (!form.username.trim() || !form.password.trim()) {
      setError("请输入用户名和密码。");
      return;
    }
    try {
      await login(form.username.trim(), form.password.trim());
      navigate("/chat");
    } catch (err) {
      setError((err as Error).message || "登录失败，请稍后重试。");
    }
  };

  return (
    <main className="login-page">
      <div className="login-page__theme"><ThemeToggle /></div>
      <section className="login-card">
        <div className="login-card__brand" aria-hidden="true">R</div>
        <h1>登录 Ragent</h1>
        <p>使用你的账号继续访问知识问答。</p>

        <form className="login-form" onSubmit={handleSubmit}>
          <div className="login-field">
            <label htmlFor="username">用户名</label>
            <Input
              id="username"
              value={form.username}
              onChange={(event) => setForm((prev) => ({ ...prev, username: event.target.value }))}
              placeholder="请输入用户名"
              autoComplete="username"
              autoFocus
            />
          </div>
          <div className="login-field">
            <label htmlFor="password">密码</label>
            <div className="login-password">
              <Input
                id="password"
                type={showPassword ? "text" : "password"}
                value={form.password}
                onChange={(event) => setForm((prev) => ({ ...prev, password: event.target.value }))}
                placeholder="请输入密码"
                autoComplete="current-password"
              />
              <button
                type="button"
                onClick={() => setShowPassword((prev) => !prev)}
                aria-label={showPassword ? "隐藏密码" : "显示密码"}
              >
                {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
              </button>
            </div>
          </div>
          {error ? <p className="login-error" role="alert">{error}</p> : null}
          <Button type="submit" className="w-full rounded-lg shadow-none" disabled={isLoading}>
            {isLoading ? "正在登录…" : "登录"}
          </Button>
        </form>
      </section>
    </main>
  );
}
